package lk.ijse.finalproject.util;

public enum Routes {
    CUSTOMER,EMPLOYEE, LOGIN, ADMIN, HOME, ADDEMPLOYEE, STORE, ADDITEM, RAWMATERIAL, PAYMENT, SUPPLIER, ADDSUPPLIER,
    ADDCUSTOMER, ADDMATERIAL, ADDPAYMENT, ORDER, ORDERDETAIL
}
